version: "3"
services:

  py4jserver:
    build:
      context: ./
      dockerfile: py4jserver/Dockerfile
    container_name: "py4jserver"

  jupyter:
    build: notebooks
    container_name: "notebook"
    ports:
      - "8888:8888"
    volumes:
      - "./:/home/jovyan/myspace"
    environment:
      - JUPYTER_ENABLE_LAB=yes
    links:
      - py4jserver
    depends_on:
      - py4jserver

